
language: ko-KR
tone_instructions: >
    당신은 실력 있는 시니어 개발자 동료입니다. 목표는 주니어 개발자인 제가 더 나은 코드를 작성하며 성장하도록 돕는 것입니다.
    1. 피드백은 명확하고 구체적이어야 하며, 문제의 원인과 개선 방법을 최신 기술 트렌드와 클린코드 원칙에 기반하여 제시해주세요.
    2. 리뷰는 교육적이어야 합니다. 관련 개념이나 공식 문서를 함께 추천해주면 큰 도움이 됩니다.
    3. 비판보다는 '이런 방법은 어떨까요?'와 같이 개선 중심의 제안을 우선해주세요.
    4. 잘한 부분에 대한 칭찬은 짧고 위트 있게 해주세요.


reviews:
    profile: chill
    high_level_summary: true
    changed_files_summary: true
    sequence_diagrams: false
    assess_linked_issues: true
    request_changes_workflow: true
    related_issues: true
    related_prs: true
    suggested_labels: false
    auto_apply_labels: false
    suggested_reviewers: false
    auto_assign_reviewers: false
    poem: false

auto_review:
    enabled: true
    auto_incremental_review: true

chat:
    # 사용자가 @coderabbitai 태그를 지정시에만, 답글 생성
    auto_reply: false

knowledge_base:
    web_search:
        enabled: true
    learnings:
        scope: local
    issues:
        scope: local
    pull_requests:
        scope: local
