name: Run KtLint with reviewdog
on: [ pull_request ]
jobs:
  ktlint:
    name: Check Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: ktlint
        uses: reviewdog/action-gradle@v1
        with:
          github_token: ${{ secrets.REVIEWDOG_GITHUB_TOKEN }}
          gradle_command: ktlintCheck
          level: warning
          reporter: github-pr-review