name: Deploy to Firebase

on:
  workflow_dispatch:
    inputs:
      release_notes:
        type: string
        required: true
        default: 'Manual Debug Build'
        description: 'Release Notes'

jobs:
  build:
    name: Building and distributing app
    runs-on: ubuntu-latest
    env:
      GOOGLE_SERVER_CLIENT_ID: ${{ secrets.GOOGLE_SERVER_CLIENT_ID }}
      MOOI_DEV_SERVER_URL: ${{ secrets.MOOI_DEV_SERVER_URL }}
      KAKAO_NATIVE_APP_KEY: ${{ secrets.KAKAO_NATIVE_APP_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Create Google Services JSON File
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $GOOGLE_SERVICES_JSON | base64 -di > app/google-services.json

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name:  Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name:  Build Debug APK only
        run: ./gradlew assembleDebug

      - name: Upload Artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          # groups: "testers(team)"
          file: app/build/outputs/apk/debug/app-debug.apk
          releaseNotes: ${{ inputs.release_notes }}
